name: perpustakaan_digital
description: Aplikasi perpustakaan digital dengan fitur login, register, dan logout tanpa Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Database local
  sqflite: ^2.2.8
  sqflite_common_ffi: ^2.2.5
  path_provider: ^2.0.15
  path: ^1.8.2
  
  # Network
  http: ^0.13.6
  cached_network_image: ^3.2.3
  
  # Auth & Security
  crypto: ^3.0.3
  
  # State Management
  provider: ^6.0.5
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  
  # Sensors & Location
  sensors_plus: ^3.0.2
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  
  # UI
  flutter_svg: ^2.0.5
  shimmer: ^3.0.0
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/